source "https://rubygems.org"

ruby "~> 3.3"

gem "rails", "~> 7.1.3"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "rack-cors"
gem "kaminari"
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri]
  gem "rspec-rails"
  gem "factory_bot_rails"
end
